EXTRA_CFLAGS += -I$(TOP)/sys/inc
EXTRA_CFLAGS += -I$(TOP)/sys

${KMPP_SRC}-objs += sys/kmpp_dq.o \
                    sys/kmpp_ioctl.o \
                    sys/kmpp_mem_pool.o \
                    sys/kmpp_obj.o \
                    sys/kmpp_shm.o \
                    sys/kmpp_sym.o \
                    sys/kmpp_sys.o \
                    sys/kmpp_trie.o
