EXTRA_CFLAGS += -I${TOP}/include
EXTRA_CFLAGS += -I${TOP}/osal/inc
EXTRA_CFLAGS += -I${TOP}/kmpp/inc
EXTRA_CFLAGS += -I${TOP}/kmpp/base/inc
EXTRA_CFLAGS += -I${TOP}/vcodec
EXTRA_CFLAGS += -I${TOP}/vcodec/inc
EXTRA_CFLAGS += -I${TOP}/vcodec/osal/inc

kmpi_vsp_test-objs := test/kmpi_vsp_test/kmpi_vsp_test.o

obj-m += kmpi_vsp_test.o
