EXTRA_CFLAGS += -I${TOP}/inc
EXTRA_CFLAGS += -I${TOP}/osal/inc
EXTRA_CFLAGS += -I${TOP}/kmpp/inc
EXTRA_CFLAGS += -I${TOP}/kmpp/base/inc
EXTRA_CFLAGS += -I${TOP}/vcodec
EXTRA_CFLAGS += -I${TOP}/vcodec/inc
EXTRA_CFLAGS += -I${TOP}/vcodec/osal/inc

kmpp_enc_test-objs := test/kmpp_enc_test/kmpp_enc_test.o

obj-m += kmpp_enc_test.o
