EXTRA_CFLAGS += -I$(TOP)/osal
EXTRA_CFLAGS += -I$(TOP)/include
EXTRA_CFLAGS += -I$(TOP)/osal/inc
EXTRA_CFLAGS += -mno-outline-atomics

${KMPP_SRC}-objs += osal/kmpp_atomic.o \
                    osal/kmpp_bitops.o \
                    osal/kmpp_clk.o \
                    osal/kmpp_cls.o \
                    osal/kmpp_mem.o \
                    osal/kmpp_log.o \
                    osal/kmpp_mutex.o \
                    osal/kmpp_spinlock.o \
                    osal/kmpp_completion.o \
                    osal/kmpp_delay.o \
                    osal/kmpp_dmabuf.o \
                    osal/kmpp_dev.o \
                    osal/kmpp_env.o \
                    osal/kmpp_file.o \
                    osal/kmpp_io.o \
                    osal/kmpp_pm.o \
                    osal/kmpp_rwsem.o \
                    osal/kmpp_sema.o \
                    osal/kmpp_sthd.o \
                    osal/kmpp_string.o \
                    osal/kmpp_thread.o \
                    osal/kmpp_time.o \
                    osal/kmpp_wait.o \
                    osal/kmpp_uaccess.o \
                    osal/kmpp_osal.o \
