EXTRA_CFLAGS += -I$(TOP)/kmpp/objs/inc
EXTRA_CFLAGS += -I$(TOP)/kmpp/vsp/inc
EXTRA_CFLAGS += -I$(TOP)/vproc/pp
EXTRA_CFLAGS += -I$(TOP)/kmpp/inc

${KMPP_SRC}-objs += kmpp/objs/kmpp_buffer.o \
                    kmpp/objs/kmpp_frame.o \
                    kmpp/objs/kmpp_packet.o \
                    kmpp/objs/kmpp_venc_objs.o \
                    kmpp/objs/kmpp_vsp_objs.o \
                    kmpp/objs/kmpp_meta.o \
                    kmpp/vsp/kmpp_vsp.o \
                    kmpp/vsp/kmpi_vsp.o
