EXTRA_CFLAGS += -I$(TOP)/kmpp/objs/inc
EXTRA_CFLAGS += -I$(TOP)/kmpp/inc

${KMPP_SRC}-objs += kmpp/objs/kmpp_frame.o \
                    kmpp/objs/kmpp_venc_objs.o \
                    kmpp/objs/kmpp_meta.o